repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.0
    hooks:
      - id: gitleaks
        name: check for secrets
        entry: gitleaks protect --staged --verbose
        language: system
        pass_filenames: false